-- MySQL Script generated by MySQL Workbench
-- Thu May 19 21:18:11 2022
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tecnocom
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tecnocom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tecnocom` ;
USE `tecnocom` ;

-- -----------------------------------------------------
-- Table `tecnocom`.`Promos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecnocom`.`Promos` (
  `promoId` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `ultimaActualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`promoId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tecnocom`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecnocom`.`pais` (
  `paisId` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(50) NOT NULL,
  `ultimaActualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`paisId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tecnocom`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecnocom`.`provincia` (
  `provinciaId` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `provincia` VARCHAR(50) NOT NULL,
  `paisId` SMALLINT UNSIGNED NOT NULL,
  `ultimaActualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`provinciaId`),
  INDEX `fkProvinciaPaisIdx` (`paisId` ASC),
  CONSTRAINT `fkProvinciaPais`
    FOREIGN KEY (`paisId`)
    REFERENCES `tecnocom`.`pais` (`paisId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tecnocom`.`localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecnocom`.`localidad` (
  `localidadId` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `localidad` VARCHAR(50) NOT NULL,
  `provinciaId` SMALLINT UNSIGNED NOT NULL,
  `ultimaActualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`localidadId`),
  INDEX `fkLocalidadProvinciaIdx` (`provinciaId` ASC),
  CONSTRAINT `fkLocalidadProvincia`
    FOREIGN KEY (`provinciaId`)
    REFERENCES `tecnocom`.`provincia` (`provinciaId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tecnocom`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecnocom`.`direccion` (
  `direccionId` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(50) NOT NULL,
  `localidadId` SMALLINT UNSIGNED NOT NULL,
  `codigoPostal` VARCHAR(10) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `ultimaActualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`direccionId`),
  INDEX `fkDireccionProviniciaIdx` (`localidadId` ASC),
  CONSTRAINT `fkDireccionProvinicia`
    FOREIGN KEY (`localidadId`)
    REFERENCES `tecnocom`.`localidad` (`localidadId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tecnocom`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecnocom`.`categorias` (
  `categoriaId` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `ultimaActualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`categoriaId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tecnocom`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecnocom`.`clientes` (
  `clienteId` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `direccionId` SMALLINT UNSIGNED NOT NULL,
  `fechaCreacion` DATETIME NOT NULL,
  `dni` INT NULL,
  `nombreUsuario` VARCHAR(45) NULL,
  `ultimaActualizacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`clienteId`),
  INDEX `IdxFkDireccionIdx` (`direccionId` ASC),
  CONSTRAINT `fkClientesDireccion`
    FOREIGN KEY (`direccionId`)
    REFERENCES `tecnocom`.`direccion` (`direccionId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Table storing all customers. Holds foreign keys to the address table and the store table where this customer is registered.\n\nBasic information about the customer like first and last name are stored in the table itself. Same for the date the record was created and when the information was last updated.';


-- -----------------------------------------------------
-- Table `tecnocom`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecnocom`.`productos` (
  `productoId` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` TEXT NULL,
  `precio` DECIMAL(15,2) NOT NULL DEFAULT 19.99,
  `stock` INT NOT NULL,
  `imagen` BLOB NULL,
  `descuento` TINYINT NULL,
  `ultimaActualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_title` (`nombre` ASC),
  PRIMARY KEY (`productoId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tecnocom`.`ProductosPromos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecnocom`.`ProductosPromos` (
  `promoId` SMALLINT UNSIGNED NOT NULL,
  `productoId` SMALLINT UNSIGNED NOT NULL,
  `ultimaActualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`promoId`, `productoId`),
  INDEX `idx_fk_film_id` (`productoId` ASC),
  INDEX `fk_film_actor_actor_idx` (`promoId` ASC),
  CONSTRAINT `fk_film_actor_actor`
    FOREIGN KEY (`promoId`)
    REFERENCES `tecnocom`.`Promos` (`promoId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_film_actor_film`
    FOREIGN KEY (`productoId`)
    REFERENCES `tecnocom`.`productos` (`productoId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tecnocom`.`categoriasProductos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecnocom`.`categoriasProductos` (
  `productoId` SMALLINT UNSIGNED NOT NULL,
  `categoriaId` TINYINT UNSIGNED NOT NULL,
  `ultimaActualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`productoId`, `categoriaId`),
  INDEX `fkProductosCategoriasCategoriasIdx` (`categoriaId` ASC),
  INDEX `fkproductosCategoriasProductosIdx` (`productoId` ASC),
  CONSTRAINT `fk_film_category_film`
    FOREIGN KEY (`productoId`)
    REFERENCES `tecnocom`.`productos` (`productoId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_film_category_category`
    FOREIGN KEY (`categoriaId`)
    REFERENCES `tecnocom`.`categorias` (`categoriaId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tecnocom`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecnocom`.`usuarios` (
  `usuarioId` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `direccionId` SMALLINT UNSIGNED NOT NULL,
  `imagen` BLOB NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT TRUE,
  `nombreUsuario` VARCHAR(16) NOT NULL,
  `claveIngreso` VARCHAR(40) BINARY NULL DEFAULT NULL,
  `ultimaActualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`usuarioId`),
  INDEX `idx_fk_address_id` (`direccionId` ASC),
  CONSTRAINT `fk_staff_address`
    FOREIGN KEY (`direccionId`)
    REFERENCES `tecnocom`.`direccion` (`direccionId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tecnocom`.`usuariosProductos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecnocom`.`usuariosProductos` (
  `usuarioId` TINYINT UNSIGNED NOT NULL,
  `productoId` SMALLINT UNSIGNED NOT NULL,
  `ultimaActualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`usuarioId`, `productoId`),
  INDEX `fk_usuariosProductos_usuarios1_idx` (`usuarioId` ASC),
  INDEX `fk_usuariosProductos_productos1_idx` (`productoId` ASC),
  CONSTRAINT `fk_usuariosProductos_usuarios1`
    FOREIGN KEY (`usuarioId`)
    REFERENCES `tecnocom`.`usuarios` (`usuarioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuariosProductos_productos1`
    FOREIGN KEY (`productoId`)
    REFERENCES `tecnocom`.`productos` (`productoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tecnocom`.`clientes_has_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecnocom`.`clientes_has_productos` (
  `clientes_clienteId` SMALLINT UNSIGNED NOT NULL,
  `productos_productoId` SMALLINT UNSIGNED NOT NULL,
  `modoDePago` VARCHAR(45) NOT NULL,
  `precio` DECIMAL(15,2) NULL,
  `descuento` TINYINT NULL,
  `promo` VARCHAR(45) NOT NULL,
  `ultimaActualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`clientes_clienteId`, `productos_productoId`),
  INDEX `fk_clientes_has_productos_productos1_idx` (`productos_productoId` ASC),
  INDEX `fk_clientes_has_productos_clientes1_idx` (`clientes_clienteId` ASC),
  CONSTRAINT `fk_clientes_has_productos_clientes1`
    FOREIGN KEY (`clientes_clienteId`)
    REFERENCES `tecnocom`.`clientes` (`clienteId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientes_has_productos_productos1`
    FOREIGN KEY (`productos_productoId`)
    REFERENCES `tecnocom`.`productos` (`productoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `tecnocom`;

DELIMITER $$
USE `tecnocom`$$

CREATE TRIGGER `ins_film` AFTER INSERT ON `film` FOR EACH ROW BEGIN
    INSERT INTO film_text (film_id, title, description)
        VALUES (new.film_id, new.title, new.description);
  END$$

USE `tecnocom`$$

CREATE TRIGGER `upd_film` AFTER UPDATE ON `film` FOR EACH ROW BEGIN
    IF (old.title != new.title) or (old.description != new.description)
    THEN
        UPDATE film_text
            SET title=new.title,
                description=new.description,
                film_id=new.film_id
        WHERE film_id=old.film_id;
    END IF;
  END$$

USE `tecnocom`$$

CREATE TRIGGER `del_film` AFTER DELETE ON `film` FOR EACH ROW BEGIN
    DELETE FROM film_text WHERE film_id = old.film_id;
  END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
